#!/bin/sh

output_config() {
    echo "graph_title Nvidia GPU Framebuffer Memory"
    echo "graph_args --base 1024 --rigid --lower-limit 0 --upper-limit 4035"
    echo "graph_category gpu"
    echo "graph_info nvidia-smi output"
    echo "graph_vlabel MiB"
    echo "graph_total Total"
    echo "graph_scale no"
    echo "used.label used"
    echo "used.draw AREA"
    echo "used.min 0"
    echo "used.type GAUGE"
    echo "free.label free"
    echo "free.draw STACK"
    echo "free.min 0"
    echo "free.type GAUGE"
}

output_values() {
    smi_output="$(nvidia-smi --format=csv --query-gpu=memory.used,memory.free | tail -1)"
    printf "used.value %d\n" $(echo $smi_output | cut -d',' -f1 | cut -d' ' -f1)
    printf "free.value %d\n" $(echo $smi_output | cut -d',' -f2 | xargs | cut -d' ' -f1)
}

output_usage() {
    printf >&2 "%s - munin plugin to graph an example value\n" ${0##*/}
    printf >&2 "Usage: %s [config]\n" ${0##*/}
}

case $# in
    0)
        output_values
        ;;
    1)
        case $1 in
            config)
                output_config
                ;;
            *)
                output_usage
                exit 1
                ;;
        esac
        ;;
    *)
        output_usage
        exit 1
        ;;
esac
